// Builds game/js/levels.js: a fixed, verified campaign of levels.
// Usage: node tools/generate-levels.mjs [count]
import { writeFileSync } from 'node:fs';
import { makeRng, generate, encodeLevel, makeLevel, solve, checkSolution, isStronglyConnected, difficultyFor } from '../game/js/levelgen.js';

const COUNT = Number(process.argv[2] || 200);

// Hand-made tutorial levels (rows of '#'/'.', S = start).
const HAND = [
  ['S....', '####.', '####.'],
  ['....S', '.###.', '.#...', '.#.##', '...##'],
  ['S....#', '####.#', '.....#', '.#####', '......'],
];

function fromRows(rows) {
  const h = rows.length,
    w = rows[0].length;
  let cells = '',
    sx = 0,
    sy = 0;
  rows.forEach((r, y) =>
    [...r].forEach((c, x) => {
      if (c === 'S') {
        sx = x;
        sy = y;
      }
      cells += c === '#' ? '#' : '.';
    }),
  );
  const lv = makeLevel(w, h, cells, sx, sy);
  const sol = solve(lv, sx, sy, null, 5000);
  if (!sol || !isStronglyConnected(lv)) throw new Error('Hand level unsolvable: ' + rows.join('/'));
  lv.par = sol.length;
  return lv;
}

const levels = HAND.map(fromRows);
const seen = new Set(levels.map(encodeLevel));
for (let n = levels.length + 1; levels.length < COUNT; n++) {
  const d = difficultyFor(n);
  const rng = makeRng(0x5eed + n * 7919);
  let lv = null;
  for (let k = 0; !lv && k < 20; k++) {
    lv = generate(rng, { w: d.w, h: d.h, moves: d.moves, beam: 4000 });
    if (lv && seen.has(encodeLevel(lv))) lv = null;
  }
  if (!lv) throw new Error('failed to generate level ' + n);
  if (!checkSolution(lv, lv.solution)) throw new Error('bad solution ' + n);
  seen.add(encodeLevel(lv));
  levels.push(lv);
  if (n % 20 === 0) console.log(`level ${n}: ${lv.w}x${lv.h} cells=${lv.floorCount} par=${lv.par}`);
}

const out = `// Generated by tools/generate-levels.mjs — do not edit by hand.
// Format: "w,h,startX,startY,par:cells" with cells as '#' (wall) / '.' (floor), row-major.
export const LEVELS = ${JSON.stringify(levels.map(encodeLevel), null, 0).replace(/","/g, '",\n"')};
`;
writeFileSync(new URL('../game/js/levels.js', import.meta.url), out);
console.log(`wrote ${levels.length} levels`);
